name: flutter_firebase
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter
  font_awesome_flutter: ^10.7.0
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  google_sign_in: ^6.2.1
  cloud_firestore: ^5.4.4
  table_calendar: ^3.1.2
  cupertino_icons: ^1.0.8
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
