// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD_h3Vn0WSHNLL4emzAY3Ptb4Xkx58dFuk',
    appId: '1:520051713984:web:222268fcc581cbcec18a25',
    messagingSenderId: '520051713984',
    projectId: 'fic-satou-project1',
    authDomain: 'fic-satou-project1.firebaseapp.com',
    storageBucket: 'fic-satou-project1.appspot.com',
    measurementId: 'G-1FPDWCCKLK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZH4Pq2Ki29LBopcY9nKYOQnN7xQM2PuI',
    appId: '1:520051713984:android:e2b80f78c15df22ec18a25',
    messagingSenderId: '520051713984',
    projectId: 'fic-satou-project1',
    storageBucket: 'fic-satou-project1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBjZDhJ8AFRMheDpFnZ24DQrG1Tgw1x2Oc',
    appId: '1:557037663378:ios:0a0588927811c28444224b',
    messagingSenderId: '557037663378',
    projectId: 'fic-shitamichi-project1-376a4',
    storageBucket: 'fic-shitamichi-project1-376a4.appspot.com',
    iosBundleId: 'com.example.flutterFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBjZDhJ8AFRMheDpFnZ24DQrG1Tgw1x2Oc',
    appId: '1:557037663378:ios:0a0588927811c28444224b',
    messagingSenderId: '557037663378',
    projectId: 'fic-shitamichi-project1-376a4',
    storageBucket: 'fic-shitamichi-project1-376a4.appspot.com',
    iosBundleId: 'com.example.flutterFirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyASSKPM2M8FuBV-o6QZguI7qLDTbl3_Q7g',
    appId: '1:659728101399:web:001236f71c5a822738ac52',
    messagingSenderId: '659728101399',
    projectId: 'fic-ueno-project',
    authDomain: 'fic-ueno-project.firebaseapp.com',
    storageBucket: 'fic-ueno-project.appspot.com',
    measurementId: 'G-KC3HWGGLXM',
  );

}